import { escapeHtml, resolveImage } from '../../js/utils.js?v=3';

const TOTAL=20;
const BEST_KEY='twcheer_recognition_best_v1';
const OVERLAY='src/assets/recognition/cheerleader-overlay.webp';
const EXCLUDED=/團長|吉祥物|主持|主播|經紀|經理|教練|staff|mascot|host|manager|coach/i;
let session=null;
let timer=null;
const shuffle=(items)=>[...items].sort(()=>Math.random()-.5);
const nameOf=(girl)=>girl.realname||girl.nickname||'未命名女孩';
const categoryOf=(girl)=>{const value=String(girl.sport||girl.team||'').toLowerCase();if(/棒|baseball|cpbl/.test(value))return '棒球';if(/籃|basketball|p\.league|t1/.test(value))return '籃球';if(/排|volleyball/.test(value))return '排球';return '其他';};
const eligible=(data)=>(data.girls||[]).filter((girl)=>!EXCLUDED.test(`${girl.realname||''} ${girl.nickname||''} ${girl.team||''}`)&&(girl.realname||girl.nickname)&&(girl.img||girl.realname));
function questions(data){const pool=shuffle(eligible(data));if(pool.length<4)return[];return Array.from({length:TOTAL},(_,index)=>{const answer=pool[index%pool.length];return{answer,category:categoryOf(answer),options:shuffle([answer,...shuffle(pool.filter((girl)=>girl.uid!==answer.uid)).slice(0,3)])};});}
function best(){try{return JSON.parse(localStorage.getItem(BEST_KEY)||'null');}catch(_){return null;}}
function saveBest(result){const old=best();if(!old||result.score>old.score||(result.score===old.score&&result.accuracy>old.accuracy))localStorage.setItem(BEST_KEY,JSON.stringify(result));return best();}
function start(data){const list=questions(data);session=list.length?{phase:'quiz',questions:list,index:0,score:0,answers:[]}:null;return Boolean(session);}
function result(){const byCategory={};for(const answer of session.answers){byCategory[answer.category]??={correct:0,total:0};byCategory[answer.category].total+=1;if(answer.correct)byCategory[answer.category].correct+=1;}return{score:session.score,total:session.questions.length,accuracy:Math.round(session.score/session.questions.length*100),byCategory,timestamp:Date.now()};}
function finish(){session.result=result();session.phase='result';session.best=saveBest(session.result);}
function titleFor(score,total){const ratio=score/total;if(ratio>=.9)return'應援神眼';if(ratio>=.75)return'球場識人王';if(ratio>=.6)return'應援觀察家';if(ratio>=.4)return'熱血新秀';return'初登場應援者';}
function message(score,total){const ratio=score/total;if(ratio>=.9)return'你的觀察力已經站上主場中央，這份名單幾乎沒有漏網之魚。';if(ratio>=.75)return'很穩的應援直覺，再挑戰一次就有機會把全場女孩都認出來。';if(ratio>=.5)return'你已經抓到不少關鍵線索，繼續累積每一場應援記憶。';return'每一次答題都是新的應援線索，記住她們的名字再回來挑戰。';}
function renderHub(){return`<div class="games-page"><div class="games-hero"><div class="games-hero-copy"><span class="eyebrow">TWC CHEERLEADER · PLAYGROUND</span><h2>把喜歡的應援，<br><em>玩成一場勝負。</em></h2><p>四種互動玩法，從認出女孩到組出夢幻陣容，現在就開始你的球場之旅。</p><button class="primary-button" data-action="start-recognition">開始認人王</button></div><div class="games-hero-line" aria-hidden="true"></div></div><section class="game-entries"><button class="game-entry game-entry--featured" data-action="start-recognition"><span class="game-entry-index">01</span><span><strong>啦啦隊認人王</strong><small>RECOGNITION QUIZ · 20 題快速挑戰</small></span><span class="game-entry-arrow">↗</span></button><button class="game-entry" data-route="minigame"><span class="game-entry-index">02</span><span><strong>殘酷二選一</strong><small>CRUEL CHOICE · 絕對本命對決</small></span><span class="game-entry-arrow">↗</span></button><button class="game-entry" data-route="dreamteam"><span class="game-entry-index">03</span><span><strong>夢幻陣容</strong><small>DREAM TEAM · 排出你的先發名單</small></span><span class="game-entry-arrow">↗</span></button><button class="game-entry" data-route="allstar"><span class="game-entry-index">04</span><span><strong>全民應援大賞</strong><small>ALL-STAR · 看見全場人氣</small></span><span class="game-entry-arrow">↗</span></button></section><div class="games-note"><span>LOCAL PLAY</span><p>認人王成績與最佳紀錄只保存在這台裝置，不需要登入。</p></div></div>`;}
function renderQuiz(){const q=session.questions[session.index];const progress=Math.round(session.index/session.questions.length*100);return`<div class="recognition-page"><div class="quiz-topline"><button class="text-button" data-action="back-games">← 遊戲中心</button><span>QUESTION ${String(session.index+1).padStart(2,'0')} / ${session.questions.length}</span><strong>${session.score} 分</strong></div><div class="quiz-progress"><span style="width:${progress}%"></span></div><div class="quiz-heading"><span class="eyebrow">RECOGNITION QUIZ</span><h2>這位女孩是誰？</h2><p>從她的應援身影，找出正確姓名。</p></div><div class="quiz-card ${session.selected?'is-answered':''}"><div class="quiz-photo-wrap"><img src="${escapeHtml(resolveImage(q.answer.img,q.answer.realname)||'')}" alt="待辨識的啦啦隊女孩" class="quiz-photo" onerror="this.style.display='none'"><div class="quiz-photo-shade"></div><span class="quiz-category">${escapeHtml(q.category)} · CHEER</span></div><div class="quiz-options">${q.options.map((option)=>`<button class="quiz-option ${session.selected?(option.uid===q.answer.uid?'is-correct':option.uid===session.selected?'is-wrong':''):''}" data-action="answer-recognition" data-uid="${escapeHtml(option.uid)}" ${session.selected?'disabled':''}><span>${escapeHtml(nameOf(option))}</span>${session.selected&&option.uid===q.answer.uid?'<b>正確</b>':''}</button>`).join('')}</div>${session.selected?`<p class="quiz-feedback ${session.lastCorrect?'good':'bad'}">${session.lastCorrect?'答對了，下一題即將開始。':`正確答案是 ${escapeHtml(nameOf(q.answer))}。`}</p>`:''}</div></div>`;}
function categories(result){return Object.entries(result.byCategory).filter(([,value])=>value.total).map(([key,value])=>`<div class="result-category"><span>${escapeHtml(key)}</span><strong>${value.correct} / ${value.total}</strong><small>${Math.round(value.correct/value.total*100)}%</small></div>`).join('');}
function review(){const wrong=session.answers.filter((answer)=>!answer.correct);return`<section class="wrong-review"><div class="result-section-heading"><span>REVIEW</span><h3>錯題回顧 · ${wrong.length} 題</h3></div>${wrong.length?wrong.map((answer)=>`<article><span class="wrong-number">${String(answer.index+1).padStart(2,'0')}</span><div><strong>${escapeHtml(nameOf(answer.given))}</strong><small>你的答案</small><p>正確答案：${escapeHtml(nameOf(answer.question.answer))}</p></div></article>`).join(''):'<p class="review-empty">這次全部答對，沒有錯題需要回顧。</p>'}</section>`;}
function renderResult(){const r=session.result;const bestResult=best();return`<div class="recognition-page result-page"><div class="result-card"><div class="result-copy"><span class="eyebrow">TWC CHEERLEADER</span><span class="result-overline">RECOGNITION QUIZ</span><h2>啦啦隊認人王</h2><div class="result-title">${titleFor(r.score,r.total)}</div><div class="result-score"><strong>${r.score}</strong><span>/ ${r.total}</span></div><div class="result-metrics"><div><span>正確率</span><strong>${r.accuracy}%</strong></div><div><span>本機最佳</span><strong>${bestResult?`${bestResult.score} / ${bestResult.total}`:'尚無紀錄'}</strong></div></div><p class="result-message">${message(r.score,r.total)}</p></div><div class="result-person"><img src="${OVERLAY}" alt="TWC Cheerleader" decoding="async"></div><div class="result-brand">TWC CHEERLEADER <span>·</span> RECOGNITION</div></div><section class="result-section"><div class="result-section-heading"><span>BREAKDOWN</span><h3>分類成績</h3></div><div class="result-categories">${categories(r)}</div></section><div class="result-actions"><button class="primary-button" data-action="retry-recognition">再挑戰一次</button><button class="secondary-button" data-action="share-recognition">產生分享圖片</button><button class="secondary-button" data-action="review-recognition">查看錯題</button><button class="text-button" data-action="back-games">返回遊戲中心</button></div>${session.reviewOpen?review():''}</div>`;}
export function renderGames(data,route){if(route?.params?.get('game')==='recognition'||session?.phase==='quiz'||session?.phase==='result'){if(!session)start(data);return session?.phase==='result'?renderResult():renderQuiz();}return renderHub();}
export async function handleGameAction(action,element,{data,render,navigate,toast}){if(action==='start-recognition'||action==='retry-recognition'){if(!start(data)){toast('目前沒有足夠的啦啦隊女孩資料可供出題。','error');return true;}navigate('games',{game:'recognition'});return true;}if(action==='back-games'){session=null;if(timer)clearTimeout(timer);navigate('games');return true;}if(action==='answer-recognition'&&session?.phase==='quiz'&&!session.selected){const q=session.questions[session.index];const given=q.options.find((option)=>option.uid===element.dataset.uid)||q.options[0];const correct=given.uid===q.answer.uid;session.selected=given.uid;session.lastCorrect=correct;if(correct)session.score+=1;session.answers.push({index:session.index,question:q,given,correct,category:q.category});render();timer=setTimeout(()=>{session.selected=null;session.index+=1;if(session.index>=session.questions.length)finish();render();},560);return true;}if(action==='review-recognition'&&session?.phase==='result'){session.reviewOpen=!session.reviewOpen;render();return true;}if(action==='share-recognition'&&session?.phase==='result'){const blob=await createShareImage(session.result);const shared=await shareBlob(blob);toast(shared?'分享圖片已準備完成':'分享圖片已下載','success');return true;}return false;}
async function loadImage(src){const image=new Image();image.src=src;await image.decode();return image;}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
export async function createShareImage(result){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d');const bg=ctx.createLinearGradient(0,0,1080,1350);bg.addColorStop(0,'#0b0818');bg.addColorStop(.55,'#21123d');bg.addColorStop(1,'#0d0a19');ctx.fillStyle=bg;ctx.fillRect(0,0,1080,1350);ctx.fillStyle='rgba(153,99,255,.16)';ctx.beginPath();ctx.arc(850,240,330,0,Math.PI*2);ctx.fill();const person=await loadImage(OVERLAY);ctx.save();ctx.globalAlpha=.9;ctx.drawImage(person,450,70,510,775);const fade=ctx.createLinearGradient(450,0,760,0);fade.addColorStop(0,'rgba(33,18,61,1)');fade.addColorStop(.48,'rgba(33,18,61,.15)');fade.addColorStop(1,'rgba(33,18,61,0)');ctx.globalCompositeOperation='destination-in';ctx.fillStyle=fade;ctx.fillRect(450,50,510,820);ctx.restore();ctx.fillStyle='#d9c8ff';ctx.font='700 28px "Microsoft JhengHei","Noto Sans TC",sans-serif';ctx.fillText('TWC CHEERLEADER',82,106);ctx.fillStyle='#9b7cff';ctx.font='700 20px Arial,sans-serif';ctx.fillText('RECOGNITION QUIZ',84,146);ctx.fillStyle='#fff';ctx.font='700 64px "Microsoft JhengHei","Noto Sans TC",sans-serif';ctx.fillText('啦啦隊認人王',80,248);ctx.fillStyle='#d4b8ff';ctx.font='700 34px "Microsoft JhengHei","Noto Sans TC",sans-serif';ctx.fillText(titleFor(result.score,result.total),84,310);ctx.fillStyle='#fff';ctx.font='900 190px Arial,sans-serif';ctx.fillText(String(result.score),78,560);ctx.fillStyle='#a89abf';ctx.font='700 62px Arial,sans-serif';ctx.fillText(`/ ${result.total}`,330,552);ctx.font='700 26px "Microsoft JhengHei","Noto Sans TC",sans-serif';ctx.fillText('答對題數',88,610);roundRect(ctx,82,670,420,106,18);ctx.fillStyle='rgba(255,255,255,.08)';ctx.fill();ctx.fillStyle='#a89abf';ctx.font='700 23px "Microsoft JhengHei","Noto Sans TC",sans-serif';ctx.fillText('正確率',110,713);ctx.fillStyle='#fff';ctx.font='900 42px Arial,sans-serif';ctx.fillText(`${result.accuracy}%`,110,755);ctx.fillStyle='#d4b8ff';ctx.font='700 25px "Microsoft JhengHei","Noto Sans TC",sans-serif';ctx.fillText('分類成績',84,868);let y=920;for(const[key,value]of Object.entries(result.byCategory)){if(!value.total)continue;ctx.fillStyle='#bca8d5';ctx.font='700 25px "Microsoft JhengHei","Noto Sans TC",sans-serif';ctx.fillText(key,90,y);ctx.fillStyle='#fff';ctx.font='900 30px Arial,sans-serif';ctx.fillText(`${value.correct} / ${value.total}`,330,y);ctx.fillStyle='#a89abf';ctx.font='600 21px Arial,sans-serif';ctx.fillText(`${Math.round(value.correct/value.total*100)}%`,470,y);y+=48;}ctx.fillStyle='#8e7aa8';ctx.font='600 21px "Microsoft JhengHei","Noto Sans TC",sans-serif';ctx.fillText('在球場之外，也記住每一位為熱愛揮手的女孩。',84,1195);ctx.fillStyle='#fff';ctx.font='800 25px Arial,sans-serif';ctx.fillText('TWC CHEERLEADER',84,1260);ctx.fillStyle='#8e7aa8';ctx.font='600 21px Arial,sans-serif';ctx.fillText('twc-cheerleader.app',84,1300);return new Promise((resolve)=>canvas.toBlob((blob)=>resolve(blob),'image/png',.92));}
async function shareBlob(blob){if(!blob)return false;const file=new File([blob],'twc-recognition-result.png',{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:'TWC CHEERLEADER 認人王成績',text:'我的啦啦隊認人王成績',files:[file]});return true;}catch(error){if(error?.name==='AbortError')return true;}}const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=file.name;link.rel='noopener';link.style.position='fixed';link.style.left='-9999px';document.body.appendChild(link);link.click();setTimeout(()=>{link.remove();URL.revokeObjectURL(url);},1500);return false;}


